export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ENABLE_2FA_BEGIN = 'ENABLE_2FA_BEGIN';
export const ENABLE_2FA_SUCCESS = 'ENABLE_2FA_SUCCESS';
export const ENABLE_2FA_FAIL = 'ENABLE_2FA_FAIL';
export const ENABLE_2FA_IDLE = 'ENABLE_2FA_IDLE';

export const DISABLE_2FA_BEGIN = 'DISABLE_2FA_BEGIN';
export const DISABLE_2FA_SUCCESS = 'DISABLE_2FA_SUCCESS';
export const DISABLE_2FA_FAIL = 'DISABLE_2FA_FAIL';
export const DISABLE_2FA_IDLE = 'DISABLE_2FA_IDLE';

export const CHANGE_USER_TFA_STATE = 'CHANGE_USER_TFA_STATE';
export const AUTH_USER_TFA = 'AUTH_USER_TFA';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_ACTIVITY_BEGIN = 'FETCH_ACTIVITY_BEGIN';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAIL = 'FETCH_ACTIVITY_FAIL';
export const INSERT_ACTIVITY = 'INSERT_ACTIVITY';

export const FETCH_DEPOSITS_BEGIN = 'FETCH_DEPOSITS_BEGIN';
export const FETCH_DEPOSITS_SUCCESS = 'FETCH_DEPOSITS_SUCCESS';
export const FETCH_DEPOSITS_FAIL = 'FETCH_DEPOSITS_FAIL';

export const FETCH_WITHDRAWALS_BEGIN = 'FETCH_WITHDRAWALS_BEGIN';
export const FETCH_WITHDRAWALS_SUCCESS = 'FETCH_WITHDRAWALS_SUCCESS';
export const FETCH_WITHDRAWALS_FAIL = 'FETCH_WITHDRAWALS_FAIL';

export const UPDATE_USER = 'UPDATE_USER';

export const DECLINE_WITHDRAWAL_BEGIN = 'DECLINE_WITHDRAWAL_BEGIN';
export const DECLINE_WITHDRAWAL_SUCCESS = 'DECLINE_WITHDRAWAL_SUCCESS';
export const DECLINE_WITHDRAWAL_FAIL = 'DECLINE_WITHDRAWAL_FAIL';
export const ACCEPT_WITHDRAWAL_FAIL = 'ACCEPT_WITHDRAWAL_FAIL';
export const ACCEPT_WITHDRAWAL_SUCCESS = 'ACCEPT_WITHDRAWAL_SUCCESS';
export const ACCEPT_WITHDRAWAL_BEGIN = 'ACCEPT_WITHDRAWAL_BEGIN';

export const UPDATE_WITHDRAWAL = 'UPDATE_WITHDRAWAL';

export const PATCH_DEPOSITS_BEGIN = 'PATCH_DEPOSITS_BEGIN';
export const PATCH_DEPOSITS_SUCCESS = 'PATCH_DEPOSITS_SUCCESS';
export const PATCH_DEPOSITS_FAIL = 'PATCH_DEPOSITS_FAIL';

export const FETCH_FAUCET_BALANCE_BEGIN = 'FETCH_FAUCET_BALANCE_BEGIN';
export const FETCH_FAUCET_BALANCE_SUCCESS = 'FETCH_FAUCET_BALANCE_SUCCESS';
export const FETCH_FAUCET_BALANCE_FAIL = 'FETCH_FAUCET_BALANCE_FAIL';

export const FETCH_BLOCKNUMBER_BEGIN = 'FETCH_BLOCKNUMBER_BEGIN';
export const FETCH_BLOCKNUMBER_SUCCESS = 'FETCH_BLOCKNUMBER_SUCCESS';
export const FETCH_BLOCKNUMBER_FAIL = 'FETCH_BLOCKNUMBER_FAIL';

export const START_SYNCBLOCKS_BEGIN = 'START_SYNCBLOCKS_BEGIN';
export const START_SYNCBLOCKS_SUCCESS = 'START_SYNCBLOCKS_SUCCESS';
export const START_SYNCBLOCKS_FAIL = 'START_SYNCBLOCKS_FAIL';

export const FETCH_ERRORS_BEGIN = 'FETCH_ERRORS_BEGIN';
export const FETCH_ERRORS_SUCCESS = 'FETCH_ERRORS_SUCCESS';
export const FETCH_ERRORS_FAIL = 'FETCH_ERRORS_FAIL';

export const FETCH_PRICECURRENCIES_BEGIN = 'FETCH_PRICECURRENCIES_BEGIN';
export const FETCH_PRICECURRENCIES_SUCCESS = 'FETCH_PRICECURRENCIES_SUCCESS';
export const FETCH_PRICECURRENCIES_FAIL = 'FETCH_PRICECURRENCIES_FAIL';

export const FETCH_USERINFO_BEGIN = 'FETCH_USERINFO_BEGIN';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAIL = 'FETCH_USERINFO_FAIL';

export const FETCH_WITHDRAWALADDRESSES_BEGIN = 'FETCH_WITHDRAWALADDRESSES_BEGIN';
export const FETCH_WITHDRAWALADDRESSES_SUCCESS = 'FETCH_WITHDRAWALADDRESSES_SUCCESS';
export const FETCH_WITHDRAWALADDRESSES_FAIL = 'FETCH_WITHDRAWALADDRESSES_FAIL';

export const FETCH_WITHDRAWALADDRESS_BEGIN = 'FETCH_WITHDRAWALADDRESS_BEGIN';
export const FETCH_WITHDRAWALADDRESS_SUCCESS = 'FETCH_WITHDRAWALADDRESS_SUCCESS';
export const FETCH_WITHDRAWALADDRESS_FAIL = 'FETCH_WITHDRAWALADDRESS_FAIL';

export const FETCH_TRANSACTIONS_BEGIN = 'FETCH_TRANSACTIONS_BEGIN';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';

export const ADD_WITHDRAWAL_ADDRESS_BEGIN = 'ADD_WITHDRAWAL_ADDRESS_BEGIN';
export const ADD_WITHDRAWAL_ADDRESS_SUCCESS = 'ADD_WITHDRAWAL_ADDRESS_SUCCESS';
export const ADD_WITHDRAWAL_ADDRESS_FAIL = 'ADD_WITHDRAWAL_ADDRESS_FAIL';

export const REMOVE_WITHDRAWAL_ADDRESS_BEGIN = 'REMOVE_WITHDRAWAL_ADDRESS_BEGIN';
export const REMOVE_WITHDRAWAL_ADDRESS_SUCCESS = 'REMOVE_WITHDRAWAL_ADDRESS_SUCCESS';
export const REMOVE_WITHDRAWAL_ADDRESS_FAIL = 'REMOVE_WITHDRAWAL_ADDRESS_FAIL';

export const REMOVE_WITHDRAWAL_ADDRESS = 'REMOVE_WITHDRAWAL_ADDRESS';
export const ADD_WITHDRAWAL_ADDRESS = 'ADD_WITHDRAWAL_ADDRESS';
export const UPDATE_WITHDRAWAL_ADDRESS = 'UPDATE_WITHDRAWAL_ADDRESS';
export const CONFIRM_WITHDRAWAL_ADDRESS = 'CONFIRM_WITHDRAWAL_ADDRESS';

export const VERIFY_WITHDRAWAL_ADDRESS_ERROR = 'VERIFY_WITHDRAWAL_ADDRESS_ERROR';
export const VERIFY_WITHDRAWAL_ADDRESS_BEGIN = 'VERIFY_WITHDRAWAL_ADDRESS_BEGIN';

export const RESEND_WITHDRAWAL_ADDRESS_BEGIN = 'RESEND_WITHDRAWAL_ADDRESS_BEGIN';
export const RESEND_WITHDRAWAL_ADDRESS_SUCCESS = 'RESEND_WITHDRAWAL_ADDRESS_SUCCESS';
export const RESEND_WITHDRAWAL_ADDRESS_FAIL = 'RESEND_WITHDRAWAL_ADDRESS_FAIL';

export const CREATE_WITHDRAWAL_BEGIN = 'CREATE_WITHDRAWAL_BEGIN';
export const CREATE_WITHDRAWAL_SUCCESS = 'CREATE_WITHDRAWAL_SUCCESS';
export const CREATE_WITHDRAWAL_FAIL = 'CREATE_WITHDRAWAL_FAIL';
export const CREATE_WITHDRAWAL = 'CREATE_WITHDRAWAL';

export const UPDATE_WALLET = 'UPDATE_WALLET';
export const INSERT_TRANSACTION = 'INSERT_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

export const FETCH_COIN_INFO_BEGIN = 'FETCH_COIN_INFO_BEGIN';
export const FETCH_COIN_INFO_SUCCESS = 'FETCH_COIN_INFO_SUCCESS';
export const FETCH_COIN_INFO_FAIL = 'FETCH_COIN_INFO_FAIL';

export const FETCH_ALL_COINS_BEGIN = 'FETCH_ALL_COINS_BEGIN';
export const FETCH_ALL_COINS_SUCCESS = 'FETCH_ALL_COINS_SUCCESS';
export const FETCH_ALL_COINS_FAIL = 'FETCH_ALL_COINS_FAIL';

export const FETCH_ALL_PRICESOURCES_BEGIN = 'FETCH_ALL_PRICESOURCES_BEGIN';
export const FETCH_ALL_PRICESOURCES_SUCCESS = 'FETCH_ALL_PRICESOURCES_SUCCESS';
export const FETCH_ALL_PRICESOURCES_FAIL = 'FETCH_ALL_PRICESOURCES_FAIL';

export const FETCH_COINPRICESOURCES_BEGIN = 'FETCH_COINPRICESOURCES_BEGIN';
export const FETCH_COINPRICESOURCES_SUCCESS = 'FETCH_COINPRICESOURCES_SUCCESS';
export const FETCH_COINPRICESOURCES_FAIL = 'FETCH_COINPRICESOURCES_FAIL';
