export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL';
export const UPDATE_ADMIN_WITHDRAWAL_SETTINGS = 'UPDATE_ADMIN_WITHDRAWAL_SETTINGS';

export const FETCH_ADMIN_WALLET_BEGIN = 'FETCH_ADMIN_WALLET_BEGIN';
export const FETCH_ADMIN_WALLET_SUCCESS = 'FETCH_ADMIN_WALLET_SUCCESS';
export const FETCH_ADMIN_WALLET_FAIL = 'FETCH_ADMIN_WALLET_FAIL';
