export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL';
export const UPDATE_ADMIN_WITHDRAWAL_SETTINGS = 'UPDATE_ADMIN_WITHDRAWAL_SETTINGS';

export const FETCH_ADMIN_WALLET_BEGIN = 'FETCH_ADMIN_WALLET_BEGIN';
export const FETCH_ADMIN_WALLET_SUCCESS = 'FETCH_ADMIN_WALLET_SUCCESS';
export const FETCH_ADMIN_WALLET_FAIL = 'FETCH_ADMIN_WALLET_FAIL';

export const UPDATE_PRICECURRENCIES = 'UPDATE_PRICECURRENCIES';
export const REMOVE_PRICECURRENCIES = 'REMOVE_PRICECURRENCIES';
export const ADD_PRICECURRENCIES = 'ADD_PRICECURRENCIES';

export const UPDATE_COINPRICESOURCE = 'UPDATE_COINPRICESOURCE';
export const REMOVE_COINPRICESOURCE = 'REMOVE_COINPRICESOURCE';
export const ADD_COINPRICESOURCE = 'ADD_COINPRICESOURCE';

export const FETCH_BLOCKCHAINS_BEGIN = 'FETCH_BLOCKCHAINS_BEGIN';
export const FETCH_BLOCKCHAINS_SUCCESS = 'FETCH_BLOCKCHAINS_SUCCESS';
export const FETCH_BLOCKCHAINS_FAIL = 'FETCH_BLOCKCHAINS_FAIL';
