export const FETCH_ADMIN_BALANCE_BEGIN = 'FETCH_ADMIN_BALANCE_BEGIN';
export const FETCH_ADMIN_BALANCE_SUCCESS = 'FETCH_ADMIN_BALANCE_SUCCESS';
export const FETCH_ADMIN_BALANCE_FAIL = 'FETCH_ADMIN_BALANCE_FAIL';

export const FETCH_ADMIN_LIABILITY_BEGIN = 'FETCH_ADMIN_LIABILITY_BEGIN';
export const FETCH_ADMIN_LIABILITY_SUCCESS = 'FETCH_ADMIN_LIABILITY_SUCCESS';
export const FETCH_ADMIN_LIABILITY_FAIL = 'FETCH_ADMIN_LIABILITY_FAIL';

export const FETCH_ADMIN_FAUCETBALANCE_BEGIN = 'FETCH_ADMIN_FAUCETBALANCE_BEGIN';
export const FETCH_ADMIN_FAUCETBALANCE_SUCCESS = 'FETCH_ADMIN_FAUCETBALANCE_SUCCESS';
export const FETCH_ADMIN_FAUCETBALANCE_FAIL = 'FETCH_ADMIN_FAUCETBALANCE_FAIL';

export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_BEGIN';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_SUCCESS';
export const FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL = 'FETCH_ADMIN_WITHDRAWAL_SETTINGS_FAIL';
export const UPDATE_ADMIN_WITHDRAWAL_SETTINGS = 'UPDATE_ADMIN_WITHDRAWAL_SETTINGS';
